name = "PowerOn"
grammar = "poweron"
# Zed matches path_suffixes case-sensitively
path_suffixes = ["po", "rg", "def", "pro", "sub", "PO", "RG", "DEF", "PRO", "SUB"]
block_comment = ["[", "]"]
tab_size = 2
hard_tabs = false

brackets = [
  { start = "(", end = ")", close = true, newline = true },
  { start = "\"", end = "\"", close = true, newline = false, not_in = ["string", "comment"] },
  { start = "[", end = "]", close = true, newline = false, not_in = ["string"] },
]
